[[LibUCL]]
arch = "aarch64"
git-tree-sha1 = "1fd367b9a5f707897b79f34669be7b2d66697ca9"
os = "macos"

    [[LibUCL.download]]
    sha256 = "701db97dbda5c081bc5ecd61ccf0c28b4313013b5c95c92472910e5d3c1a5415"
    url = "https://github.com/JuliaBinaryWrappers/LibUCL_jll.jl/releases/download/LibUCL-v0.9.2+0/LibUCL.v0.9.2.aarch64-apple-darwin.tar.gz"
[[LibUCL]]
arch = "aarch64"
git-tree-sha1 = "b0096f5b14eaff70d02ae117c403a00a400a285a"
libc = "glibc"
os = "linux"

    [[LibUCL.download]]
    sha256 = "9ad1bba14a9960edd8fe9f83f1dfda4fefa753971bcbdf11d72a8d106fb29350"
    url = "https://github.com/JuliaBinaryWrappers/LibUCL_jll.jl/releases/download/LibUCL-v0.9.2+0/LibUCL.v0.9.2.aarch64-linux-gnu.tar.gz"
[[LibUCL]]
arch = "aarch64"
git-tree-sha1 = "1a6fe2c6cc2246333a3aa571384ffcb0bc3970a8"
libc = "musl"
os = "linux"

    [[LibUCL.download]]
    sha256 = "bd1796fc817d9f2c2e4cc89d3512531d2047e993d2100e8468301f4517e05470"
    url = "https://github.com/JuliaBinaryWrappers/LibUCL_jll.jl/releases/download/LibUCL-v0.9.2+0/LibUCL.v0.9.2.aarch64-linux-musl.tar.gz"
[[LibUCL]]
arch = "aarch64"
git-tree-sha1 = "dd5f8a7d9a1b38e76ab0ebdf205a0535ac1df0d1"
os = "freebsd"

    [[LibUCL.download]]
    sha256 = "ba08ddb864c77ea7daef6b4980f66a1ed3f6006f06fabbc66ad967873f2b1d0b"
    url = "https://github.com/JuliaBinaryWrappers/LibUCL_jll.jl/releases/download/LibUCL-v0.9.2+0/LibUCL.v0.9.2.aarch64-unknown-freebsd.tar.gz"
[[LibUCL]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "b01549f16f712263c940b4e21f8fef18d7974dfb"
libc = "glibc"
os = "linux"

    [[LibUCL.download]]
    sha256 = "93093da4109741240bd95caa8033e6341eb046cf5e550eec8f1ae36a1adc1004"
    url = "https://github.com/JuliaBinaryWrappers/LibUCL_jll.jl/releases/download/LibUCL-v0.9.2+0/LibUCL.v0.9.2.armv6l-linux-gnueabihf.tar.gz"
[[LibUCL]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "8e4c45464120b597e1fffa7b0362845188160619"
libc = "musl"
os = "linux"

    [[LibUCL.download]]
    sha256 = "ffd0823cb9a468be8dad5233b7d7101d46a7893419e45c4ef89f478cec2363dd"
    url = "https://github.com/JuliaBinaryWrappers/LibUCL_jll.jl/releases/download/LibUCL-v0.9.2+0/LibUCL.v0.9.2.armv6l-linux-musleabihf.tar.gz"
[[LibUCL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "117c6c3b7b4e5f1061d28d27869f8e8ca7ad446d"
libc = "glibc"
os = "linux"

    [[LibUCL.download]]
    sha256 = "d3c1fbd2bdf6560792e508048c484c1093569f6c7fe47d0bc6778245aea1ec94"
    url = "https://github.com/JuliaBinaryWrappers/LibUCL_jll.jl/releases/download/LibUCL-v0.9.2+0/LibUCL.v0.9.2.armv7l-linux-gnueabihf.tar.gz"
[[LibUCL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a42dbfe71ed31f45eb52a4568188b0ad9c8c6189"
libc = "musl"
os = "linux"

    [[LibUCL.download]]
    sha256 = "2c20ce16aff28acf0faff0b37f21134a66b8224c2f62dcb6663235262502dd85"
    url = "https://github.com/JuliaBinaryWrappers/LibUCL_jll.jl/releases/download/LibUCL-v0.9.2+0/LibUCL.v0.9.2.armv7l-linux-musleabihf.tar.gz"
[[LibUCL]]
arch = "i686"
git-tree-sha1 = "f4279642d843176bfe1bcb8a5136d5f732a3b414"
libc = "glibc"
os = "linux"

    [[LibUCL.download]]
    sha256 = "8e830eb041d7128c7ef01b0871d49069e2ad3ff92373a1eb19ff771c0f0f1d0b"
    url = "https://github.com/JuliaBinaryWrappers/LibUCL_jll.jl/releases/download/LibUCL-v0.9.2+0/LibUCL.v0.9.2.i686-linux-gnu.tar.gz"
[[LibUCL]]
arch = "i686"
git-tree-sha1 = "d184215cfe594b0e626d11c89a49f12af65b1e8e"
libc = "musl"
os = "linux"

    [[LibUCL.download]]
    sha256 = "a8aeda53351dc0cc0ea5d503bca872d3f54379463af92174f84a2e007d27851b"
    url = "https://github.com/JuliaBinaryWrappers/LibUCL_jll.jl/releases/download/LibUCL-v0.9.2+0/LibUCL.v0.9.2.i686-linux-musl.tar.gz"
[[LibUCL]]
arch = "i686"
git-tree-sha1 = "3094fc449b7c6622c7d9c93a2207e8005d4f34be"
os = "windows"

    [[LibUCL.download]]
    sha256 = "6eeb147412a587a8557044723c09d8fcb4e96d84628d433692e8a38c9d68451c"
    url = "https://github.com/JuliaBinaryWrappers/LibUCL_jll.jl/releases/download/LibUCL-v0.9.2+0/LibUCL.v0.9.2.i686-w64-mingw32.tar.gz"
[[LibUCL]]
arch = "powerpc64le"
git-tree-sha1 = "57a721a077ce2599f4f5a0ee9e8695eacea8d11d"
libc = "glibc"
os = "linux"

    [[LibUCL.download]]
    sha256 = "7b8fb614322d10e07c0185f90b32cabc7cbaf572bb791e52ded6f89cd070caaf"
    url = "https://github.com/JuliaBinaryWrappers/LibUCL_jll.jl/releases/download/LibUCL-v0.9.2+0/LibUCL.v0.9.2.powerpc64le-linux-gnu.tar.gz"
[[LibUCL]]
arch = "riscv64"
git-tree-sha1 = "13d3e78f440cd67866039485914b7aa411d3b4ff"
libc = "glibc"
os = "linux"

    [[LibUCL.download]]
    sha256 = "17acbdf3336c26f8edf485a2eca6e5adade30fbc07c1b93ad7eac75ba3b587c8"
    url = "https://github.com/JuliaBinaryWrappers/LibUCL_jll.jl/releases/download/LibUCL-v0.9.2+0/LibUCL.v0.9.2.riscv64-linux-gnu.tar.gz"
[[LibUCL]]
arch = "x86_64"
git-tree-sha1 = "149fcc0a89f36120af2de059367fe87f9e53a8b6"
os = "macos"

    [[LibUCL.download]]
    sha256 = "511ac340ac8a628bc3f2e2b43e3a73b4b4197232cb9ee3a6be0a867f9d50704b"
    url = "https://github.com/JuliaBinaryWrappers/LibUCL_jll.jl/releases/download/LibUCL-v0.9.2+0/LibUCL.v0.9.2.x86_64-apple-darwin.tar.gz"
[[LibUCL]]
arch = "x86_64"
git-tree-sha1 = "5e27742993f2cff8d4bbd43203891ec77fe2f7c6"
libc = "glibc"
os = "linux"

    [[LibUCL.download]]
    sha256 = "45d7041fa8de7dde2ef3cc7fc6010233820031c864de5d5fc2c3882119023620"
    url = "https://github.com/JuliaBinaryWrappers/LibUCL_jll.jl/releases/download/LibUCL-v0.9.2+0/LibUCL.v0.9.2.x86_64-linux-gnu.tar.gz"
[[LibUCL]]
arch = "x86_64"
git-tree-sha1 = "71107b1bde9b07aa9111ad5d3ff609f135dcda1a"
libc = "musl"
os = "linux"

    [[LibUCL.download]]
    sha256 = "93d8af9a06272f8c11f5b49f7f24a49ac5ff513c7a5e09c0138b98d7ffb82e88"
    url = "https://github.com/JuliaBinaryWrappers/LibUCL_jll.jl/releases/download/LibUCL-v0.9.2+0/LibUCL.v0.9.2.x86_64-linux-musl.tar.gz"
[[LibUCL]]
arch = "x86_64"
git-tree-sha1 = "44d7c616893daafb2e530463566ec0dfe4080705"
os = "freebsd"

    [[LibUCL.download]]
    sha256 = "55822966b580d8c01d186db1a5df4f3fea52afc7dfc5fffe35e7e0b73cb2f5c0"
    url = "https://github.com/JuliaBinaryWrappers/LibUCL_jll.jl/releases/download/LibUCL-v0.9.2+0/LibUCL.v0.9.2.x86_64-unknown-freebsd.tar.gz"
[[LibUCL]]
arch = "x86_64"
git-tree-sha1 = "805e508526969ac8bd524f8fa01b70cc3ec636e5"
os = "windows"

    [[LibUCL.download]]
    sha256 = "c724a2e6fcc3321adcd308c9220618598e5989958baa77e8080663b48c6f05a2"
    url = "https://github.com/JuliaBinaryWrappers/LibUCL_jll.jl/releases/download/LibUCL-v0.9.2+0/LibUCL.v0.9.2.x86_64-w64-mingw32.tar.gz"
