[[LibUCL]]
arch = "aarch64"
git-tree-sha1 = "3b05d825a26e9829c35979c128a441d900fbbe64"
os = "macos"

    [[LibUCL.download]]
    sha256 = "08d004996d94b7626e921327d70d4942be4cee1fe5f70e837ab8f0ccaf6776ba"
    url = "https://github.com/JuliaBinaryWrappers/LibUCL_jll.jl/releases/download/LibUCL-v0.8.2+1/LibUCL.v0.8.2.aarch64-apple-darwin.tar.gz"
[[LibUCL]]
arch = "aarch64"
git-tree-sha1 = "d9bb09c2f9e3fa7c980315a5bf44cde669629fbe"
libc = "glibc"
os = "linux"

    [[LibUCL.download]]
    sha256 = "19f9f2822e1d89196ae72fc8857e919beab0ce65de5112b72c4365ecef1f3fdd"
    url = "https://github.com/JuliaBinaryWrappers/LibUCL_jll.jl/releases/download/LibUCL-v0.8.2+1/LibUCL.v0.8.2.aarch64-linux-gnu.tar.gz"
[[LibUCL]]
arch = "aarch64"
git-tree-sha1 = "f01062bf64742de0b0bbfb8ed71bb307e369096d"
libc = "musl"
os = "linux"

    [[LibUCL.download]]
    sha256 = "640e54782397208d34071da00b4249b4be985f5ab219a6a1789746085f24cdaf"
    url = "https://github.com/JuliaBinaryWrappers/LibUCL_jll.jl/releases/download/LibUCL-v0.8.2+1/LibUCL.v0.8.2.aarch64-linux-musl.tar.gz"
[[LibUCL]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "a566fa96c56b2ceac549a6106af46f6fcae87581"
libc = "glibc"
os = "linux"

    [[LibUCL.download]]
    sha256 = "d9a2787edeeef9febc92f193fa86ed5412675a331c200f5ca619c78efa4fef75"
    url = "https://github.com/JuliaBinaryWrappers/LibUCL_jll.jl/releases/download/LibUCL-v0.8.2+1/LibUCL.v0.8.2.armv6l-linux-gnueabihf.tar.gz"
[[LibUCL]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "e594835f37b0f7071e78b69a2edd95d9b62ad4e1"
libc = "musl"
os = "linux"

    [[LibUCL.download]]
    sha256 = "7b43581e4969520fc76ee860033294a4150d3cffa53f4589ca23b0ea42330c48"
    url = "https://github.com/JuliaBinaryWrappers/LibUCL_jll.jl/releases/download/LibUCL-v0.8.2+1/LibUCL.v0.8.2.armv6l-linux-musleabihf.tar.gz"
[[LibUCL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "5f6c3c1185e51a1df0614f20156067c82ed16d2a"
libc = "glibc"
os = "linux"

    [[LibUCL.download]]
    sha256 = "b2819ef9997fad3017661afc5f6b38f4667a5f8a90c036c1c2e364ef9316ec6f"
    url = "https://github.com/JuliaBinaryWrappers/LibUCL_jll.jl/releases/download/LibUCL-v0.8.2+1/LibUCL.v0.8.2.armv7l-linux-gnueabihf.tar.gz"
[[LibUCL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "02b23def75a74062b3d9d1ff28baf7c1a7103410"
libc = "musl"
os = "linux"

    [[LibUCL.download]]
    sha256 = "3a0248c789a8cc4879b985fa154701e1bee5d54be9ebf616f1dd254b4c1ea1f7"
    url = "https://github.com/JuliaBinaryWrappers/LibUCL_jll.jl/releases/download/LibUCL-v0.8.2+1/LibUCL.v0.8.2.armv7l-linux-musleabihf.tar.gz"
[[LibUCL]]
arch = "i686"
git-tree-sha1 = "d13df524671e0bf7475ae2eb20ae7466ebed0337"
libc = "glibc"
os = "linux"

    [[LibUCL.download]]
    sha256 = "5fae391011c7218ff262d0279a3d1f13325bbb5da61fb5ee2a13f5129067269b"
    url = "https://github.com/JuliaBinaryWrappers/LibUCL_jll.jl/releases/download/LibUCL-v0.8.2+1/LibUCL.v0.8.2.i686-linux-gnu.tar.gz"
[[LibUCL]]
arch = "i686"
git-tree-sha1 = "f89bbda16920ae86c2b0240691efe809dfa5ed05"
libc = "musl"
os = "linux"

    [[LibUCL.download]]
    sha256 = "a855ad4340d0ed45ce627050654290e0f6f75678dde105b2ba2e450573524483"
    url = "https://github.com/JuliaBinaryWrappers/LibUCL_jll.jl/releases/download/LibUCL-v0.8.2+1/LibUCL.v0.8.2.i686-linux-musl.tar.gz"
[[LibUCL]]
arch = "i686"
git-tree-sha1 = "856d0146a1a0af1141de4055f6e8c8abef6c6edb"
os = "windows"

    [[LibUCL.download]]
    sha256 = "c13e62a631f5b04c183eba0763d8d8b71ec935f4e555fb91dd390796c7f05293"
    url = "https://github.com/JuliaBinaryWrappers/LibUCL_jll.jl/releases/download/LibUCL-v0.8.2+1/LibUCL.v0.8.2.i686-w64-mingw32.tar.gz"
[[LibUCL]]
arch = "powerpc64le"
git-tree-sha1 = "69419d775d7ebd55bf6c78ca0447b5a118118442"
libc = "glibc"
os = "linux"

    [[LibUCL.download]]
    sha256 = "806da2d7c28724700dea6e7825632ced01316d7866520c1bcc1cc3ee791eabd5"
    url = "https://github.com/JuliaBinaryWrappers/LibUCL_jll.jl/releases/download/LibUCL-v0.8.2+1/LibUCL.v0.8.2.powerpc64le-linux-gnu.tar.gz"
[[LibUCL]]
arch = "x86_64"
git-tree-sha1 = "ae7c20b035006b9e0effd812f22ea5e1d57fdb01"
os = "macos"

    [[LibUCL.download]]
    sha256 = "f64a80d49bfd7b982cc3a04dc8b11eabb5613f7b01d3e844a9fb2a988bc571b9"
    url = "https://github.com/JuliaBinaryWrappers/LibUCL_jll.jl/releases/download/LibUCL-v0.8.2+1/LibUCL.v0.8.2.x86_64-apple-darwin.tar.gz"
[[LibUCL]]
arch = "x86_64"
git-tree-sha1 = "0fa542a1922ceff83b817a0ef2b103b8d7c5a2cc"
libc = "glibc"
os = "linux"

    [[LibUCL.download]]
    sha256 = "f8fe5d91d22d96e3bf6ff1d7d3ee7adb1505c53d184e7e29b3be5e85b1a811dd"
    url = "https://github.com/JuliaBinaryWrappers/LibUCL_jll.jl/releases/download/LibUCL-v0.8.2+1/LibUCL.v0.8.2.x86_64-linux-gnu.tar.gz"
[[LibUCL]]
arch = "x86_64"
git-tree-sha1 = "7f11d47b3e3f9425d7a151666854b8037b6439fc"
libc = "musl"
os = "linux"

    [[LibUCL.download]]
    sha256 = "3d5a40640f134eb34ca6e977d7356531b598a7e58d64e58e8b5b6432c1d978ec"
    url = "https://github.com/JuliaBinaryWrappers/LibUCL_jll.jl/releases/download/LibUCL-v0.8.2+1/LibUCL.v0.8.2.x86_64-linux-musl.tar.gz"
[[LibUCL]]
arch = "x86_64"
git-tree-sha1 = "c822ceac3c805b5e42f7c3eddfa18ca1d94133ea"
os = "freebsd"

    [[LibUCL.download]]
    sha256 = "b9f618b604f19077520430ff2b064f2518f3a085f3af6e9c60a7612c637190d8"
    url = "https://github.com/JuliaBinaryWrappers/LibUCL_jll.jl/releases/download/LibUCL-v0.8.2+1/LibUCL.v0.8.2.x86_64-unknown-freebsd.tar.gz"
[[LibUCL]]
arch = "x86_64"
git-tree-sha1 = "4bfc541fdeebafd371286ce3a1f9b54b035c53e9"
os = "windows"

    [[LibUCL.download]]
    sha256 = "77366e5399048f0244d6e4e50fd18080450874b93aa9e2c971ff2faea327dac1"
    url = "https://github.com/JuliaBinaryWrappers/LibUCL_jll.jl/releases/download/LibUCL-v0.8.2+1/LibUCL.v0.8.2.x86_64-w64-mingw32.tar.gz"
